### ISSUE TITLE
rewritten for attiny1604 processor

### ISSUE THREAD

**Issue by concon** [davefiddes/FuelGauge#3]
Hi David,

Thank you very much for this awesome projects, a little bit req., if you rewritten for attiny1604, i will be very glad. 

very important my grand cherokee (2004), 

Cheers,

**Comment by davefiddes** [comment]
Sorry. If you wish to use a different MCU feel free to fork the project and adapt as you wish. The core code is designed to be cross-platform and should just require a HAL for the MCU.
